#!/usr/bin/env bash
# Script: init-study-env.sh
# Category: utility
# OPSEC: N/A
# Purpose: Scaffold CRTO study directory tree on Kali study instance
# Created: auto-generated by Claude Code
# Run once at start of study period

STUDY_ROOT="/home/kali/Documents/crto-study-notes"

dirs=(
  "notes/module-notes"
  "notes/adaptix-parallel"
  "cheatsheets"
  "command-log"
  "scripts/recon"
  "scripts/credential-access"
  "scripts/lateral-movement"
  "scripts/evasion"
  "scripts/persistence"
  "scripts/utility"
  "payloads/cs-profiles"
  "payloads/bofs"
  "payloads/loaders"
  "payloads/staged"
  "loot"
  "exam-prep"
)

echo "[*] Scaffolding CRTO study tree at $STUDY_ROOT"
mkdir -p "$STUDY_ROOT"

for d in "${dirs[@]}"; do
  mkdir -p "$STUDY_ROOT/$d"
  echo "  [+] $STUDY_ROOT/$d"
done

# Create index files with headers if they don't exist
init_file() {
  local path="$1"
  local content="$2"
  [ -f "$path" ] || echo -e "$content" > "$path"
}

init_file "$STUDY_ROOT/notes/session-log.md" \
"# CRTO Study Session Log\n*Juan | Integrity360 | groupservice.co.za*\n\n---\n"

init_file "$STUDY_ROOT/scripts/README.md" \
"# Scripts Index\n\n| Name | Category | OPSEC | Purpose | Date |\n|------|----------|-------|---------|------|\n"

init_file "$STUDY_ROOT/payloads/README.md" \
"# Payloads Index\n\n| Name | Type | Arch | Listener | Defender Status | Date | Module |\n|------|------|------|----------|-----------------|------|--------|\n"

init_file "$STUDY_ROOT/loot/README.md" \
"# Loot Log\n\n| Date | Host | Cred Type | Account | Value/Hash/Note | Module |\n|------|------|-----------|---------|-----------------|--------|\n"

init_file "$STUDY_ROOT/command-log/README.md" \
"# Command Log Index\n\nOne file per study day — YYYY-MM-DD.md\n\n"

init_file "$STUDY_ROOT/exam-prep/flag-tracker.md" \
"# CRTO Exam Flag Tracker\n\n| # | Host | Flag Value | Time Captured | Technique Used | OPSEC Notes |\n|---|------|------------|---------------|----------------|-------------|\n| 1 | | | | | |\n| 2 | | | | | |\n| 3 | | | | | |\n| 4 | | | | | |\n| 5 | | | | | |\n| 6 | | | | | |\n| 7 | | | | | |\n| 8 | | | | | |\n\n**Pass threshold: 6 / 8 flags + OPSEC score**\n"

init_file "$STUDY_ROOT/exam-prep/exam-checklist.md" \
"# CRTO Exam Day Checklist\n\n## Day Before\n- [ ] Download Threat Profile from exam portal\n- [ ] Build and c2lint malleable C2 profile matching threat profile\n- [ ] Test profile in training lab — Defender ON — beacon survives\n- [ ] Note Windows Defender signature version in lab\n- [ ] Obsidian open with attack chain and flag tracker\n- [ ] Verify CTRL+ALT+SHIFT clipboard workflow in browser session\n- [ ] CS team server up — listeners active — test callback\n- [ ] Review loot/README.md from lab sessions for technique notes\n- [ ] Review command-log/ for any gotchas observed during training\n\n## Exam Start\n- [ ] Read full scope and engagement rules in-platform\n- [ ] Stand up CS team server on exam Kali\n- [ ] Configure custom C2 profile, run c2lint, test beacon callback\n- [ ] Open flag-tracker.md in second window\n\n## During Exam\n- [ ] Run OPSEC check before every non-trivial technique\n- [ ] Submit flags immediately — don't batch\n- [ ] Rest every 12h — don't burn out\n- [ ] If stuck >2h — move to another path\n- [ ] Document every command run (OPSEC score counts)\n"

# Module note stubs
modules=(
  "01-red-team-fundamentals"
  "02-c2-setup"
  "03-initial-access"
  "04-host-recon"
  "05-domain-recon"
  "06-credential-access"
  "07-lateral-movement"
  "08-privilege-escalation"
  "09-domain-dominance"
  "10-persistence"
  "11-defense-evasion"
  "12-cross-forest"
  "13-reporting"
)

for m in "${modules[@]}"; do
  f="$STUDY_ROOT/notes/module-notes/${m}.md"
  init_file "$f" "# Module: ${m//-/ }\n\n*ZPS RTO I — Notes by Juan*\n\n---\n\n## Key Techniques\n\n## CS Commands\n\n## Adaptix Equivalent\n\n## OPSEC Notes\n\n## Defender Observations\n\n## Lab Exercise Results\n"
done

# Cheatsheet stubs
sheets=(
  "cobalt-strike"
  "adaptix-c2"
  "cs-vs-adaptix"
  "active-directory"
  "kerberos"
  "lateral-movement"
  "credential-access"
  "defense-evasion"
  "persistence"
  "cross-forest"
)

for s in "${sheets[@]}"; do
  f="$STUDY_ROOT/cheatsheets/${s}.md"
  init_file "$f" "# Cheatsheet: ${s//-/ }\n\n*CRTO Study — Juan*\n\n---\n"
done

# .gitignore — keep loot and live payloads out of GitHub
cat > "$STUDY_ROOT/.gitignore" << 'EOF'
# Never push live payloads or loot
payloads/staged/
loot/
# OS noise
.DS_Store
*.swp
EOF

# .gitkeep files so empty dirs are tracked by git
for d in payloads/staged loot payloads/bofs payloads/loaders scripts/recon scripts/credential-access scripts/lateral-movement scripts/evasion scripts/persistence; do
  touch "$STUDY_ROOT/$d/.gitkeep"
done

echo ""
echo "[+] Study environment ready at $STUDY_ROOT"
echo "[+] .gitignore created — payloads/staged/ and loot/ excluded from git"
echo "[*] Next: cd $STUDY_ROOT && git add . && git commit -m 'chore: init crto study env'"
